### ISSUE TITLE
Should conda package be on omnia or choderalab binstar channels?

### ISSUE THREAD

**Issue by jchodera** [choderalab/thermopyl#15]
Any preference here?

Mechanisms for both are in place, so either is easy.

**Comment by kyleabeauchamp** [comment]
I suppose if both are in place, we can use choderalab for this one

**Comment by hainm** [comment]
I've been trying to `conda install thermopyl -c omnia` but can not found the package. It turns out (here) that the program has never been pushed to  binstar.

**Comment by jchodera** [comment]
@hainm: Thanks for catching that this isn't up yet.  We are actually only pushing `thermopyl-dev` right now, but that was (to my surprise) not working.  It should be up now here: https://binstar.org/choderalab/thermopyl-dev

**Comment by hainm** [comment]
thanks. Work for me now.

Hai

**Comment by jchodera** [comment]
@hainm You may want to wait a day or two for the final 1.0 release once we get #16 merged, since the current version is only grabbing a small fraction of the database.  We'll have the real 1.0 version posted to conda once that is fixed.

**Comment by hainm** [comment]
sure.

**Comment by jchodera** [comment]
Is this ready to cut a 1.0 release and build a non-dev conda package, @kyleabeauchamp? If you are happy with it providing what you describe in the paper, I can tackle this.

**Comment by kyleabeauchamp** [comment]
Sounds good

**Comment by jchodera** [comment]
This is done.
