### ISSUE TITLE
instructions say conda-install omnia, but it's not there.

### ISSUE THREAD

**Issue by mrshirts** [choderalab/thermopyl#25]

**Comment by kyleabeauchamp** [comment]
This looks like a bug.  @jchodera  do we want to upload packages manually or get the CI system working?  I'm not up to date on the state of the CI tools.

**Comment by bas-rustenburg** [comment]
Those instructions are probably just wrong. I don't think omnia builds thermopyl (https://github.com/omnia-md/conda-recipes). 

Looks like it's in our labs channel. https://anaconda.org/choderalab/thermopyl

**Comment by jchodera** [comment]
Fixed in #27.

**Comment by jchodera** [comment]
Thanks for chiming in here @kyleabeauchamp and @bas-rustenburg!
