### ISSUE TITLE
Add ThermoML incremental retrieval tool

### ISSUE THREAD

**Issue by jchodera** [choderalab/ThermoPyL#8]
(Just adding this hear to clear it from my inbox)

NIST now provides an RSS feed indexing all ThermoML files, indexed as one set per journal (where each journal has an XML file):
http://trc.nist.gov/RSS/

I suggest we add an incremental retrieval tool to build a local cache of ThermoML files using the following scheme:
* If no local cache exists, it downloads and unpack the tarball NIST will post if this isn't present (once NIST does so)
* On subsequent calls, or if no local cache exists but no tarball is available, it retrieves only the RSS feed XMLs, and only downloads those ThermoML files that are not currently in the local repository

This should provide users with a convenient way to stay up to date while minimizing the impact on the NIST webservers.

**Comment by kyleabeauchamp** [comment]
Implemented in #9
